### PR TITLE
Fixing display size

### PR DESCRIPTION
**Pull request by Aniket21mathur**
The activity do not fit the entire display size.

Now it fits the entire display and tested for standard resolutions.

Fixes https://github.com/sugarlabs/cardsort/issues/9

### CODE REVIEW

**Comment by quozl** [comment]
Thanks.  Tested on Ubuntu 18.04, problem persists.

Test method;
* `sugar-activity` to verify problem occurs before change,
* `git fetch origin pull/11/head && git checkout b6632e2`,
* `sugar-activity` to check if problem occurs after change; problem persists,
* 'grep Gdk.Screen *.py` to verify patch was applied; it was.

**Comment by Aniket21mathur** [comment]
Thanks!
I am not very sure about it why it happened.
Tested on Ubuntu 18.04.
Followed the same test method you described, fixed the problem for me.
Can you please specify which screen resolution you tested on ?

**Comment by quozl** [comment]
Same as in the issue; 1024x768.  Please check the commit b6632e2 by clicking on it and reading the changes to make sure all the changes you expect are present in the commit?

**Comment by Aniket21mathur** [comment]
This seems interesting, I tested again , checked the commit, things working fine on my machine :sweat_smile: .Here are screenshots for before and after change
Before:
screenshot from 2019-01-14 12-33-19
After:
screenshot from 2019-01-14 12-33-51
Thank you!

**Comment by quozl** [comment]
That's not what a fix would look like.  I'll describe the fix in the issue.

**Comment by quozl** [comment]
Also, you've been testing the activity within another desktop.  What matters most is how the activity will render when run within the Sugar desktop.

**Pull request closed without merging**
